# VENDORED verbatim from the EulerMind research repo (github.com/judeszn/EulerMind)
# at commit 8521038 - only import paths adapted. Canonical source + full
# experiment history live there. Do not edit here.
"""Delta D2 Tasks 2-4 — LP Solver, certifying Verifier, and certificates
for optimization_lp. First THEOREM-BACKED certification domain: the
solver's completeness rests on the Fundamental Theorem of Linear
Programming (a bounded feasible LP's optimum occurs at a vertex of the
feasible region), not on exhaustive enumeration of a finite candidate set
that IS the problem (as in edge_ai/CSP).

Solver (Task 2): maximize p1*x + p2*y subject to
  a1*x + b1*y <= c1, a2*x + b2*y <= c2, x >= 0, y >= 0.
Vertices are the pairwise intersections of the 4 boundary lines
(x=0, y=0, constraint1, constraint2) - up to 6 candidates, generalizing
the generator's 3-fixed-vertex shortcut to handle any relative
orientation of the two constraints, not just the dataset's typical case.

Unboundedness (Task 2, scoped): for this exact structure (2 general
halfplane constraints + non-negativity in 2D), the feasible region's
recession cone - if nontrivial - is generated by directions parallel to
one of the 4 boundary lines (a standard fact for 2D polyhedra: an
unbounded edge of a 2D polygon is parallel to the constraint that forms
it). Checking the 2 axis directions and both orientations of each
constraint's direction vector is therefore a complete check for THIS
structure - not a claim of a general n-dimensional unboundedness
algorithm.

Certificate (Task 4): the claimed optimal (x, y, profit) plus the spec;
re-checkable by re-deriving the vertex set from scratch.

Independent checker (Task 5, kept OUT of this file - see
research/D2_lp_vertical/independent_checker.py): uses the LP DUALITY
THEOREM (weak/strong duality + complementary slackness) instead of vertex
enumeration - a genuinely different theorem, not a different search
style, and it performs zero optimization/search (only arithmetic and a
small linear solve implied by the claimed answer's active-constraint
pattern).
"""

from __future__ import annotations

TOL = 1e-6


def _solve_2x2(a11, a12, a21, a22, b1, b2):
    """Cramer's rule. Returns (x, y) or None if singular."""
    det = a11 * a22 - a12 * a21
    if abs(det) < 1e-12:
        return None
    return ((b1 * a22 - b2 * a12) / det, (a11 * b2 - a21 * b1) / det)


def _feasible(spec: dict, x: float, y: float) -> bool:
    return (x >= -TOL and y >= -TOL
           and spec["a1"] * x + spec["b1"] * y <= spec["c1"] + TOL
           and spec["a2"] * x + spec["b2"] * y <= spec["c2"] + TOL)


def _candidate_vertices(spec: dict) -> list[tuple[float, float]]:
    """All pairwise intersections of the 4 boundary lines
    {x=0, y=0, a1x+b1y=c1, a2x+b2y=c2}. Generic 2D vertex enumeration -
    not the generator's 3-fixed-vertex shortcut."""
    a1, b1, c1 = spec["a1"], spec["b1"], spec["c1"]
    a2, b2, c2 = spec["a2"], spec["b2"], spec["c2"]
    lines = [(1.0, 0.0, 0.0), (0.0, 1.0, 0.0), (a1, b1, c1), (a2, b2, c2)]
    verts = []
    for i in range(len(lines)):
        for j in range(i + 1, len(lines)):
            A1, B1, C1 = lines[i]
            A2, B2, C2 = lines[j]
            pt = _solve_2x2(A1, B1, A2, B2, C1, C2)
            if pt is not None:
                verts.append(pt)
    return verts


def _recession_directions(spec: dict) -> list[tuple[float, float]]:
    a1, b1 = spec["a1"], spec["b1"]
    a2, b2 = spec["a2"], spec["b2"]
    return [(1.0, 0.0), (0.0, 1.0),
           (-b1, a1), (b1, -a1), (-b2, a2), (b2, -a2)]


def _is_unbounded(spec: dict) -> bool:
    a1, b1, a2, b2 = spec["a1"], spec["b1"], spec["a2"], spec["b2"]
    p1, p2 = spec["p1"], spec["p2"]
    for dx, dy in _recession_directions(spec):
        if dx < -TOL or dy < -TOL:
            continue
        if abs(dx) <= TOL and abs(dy) <= TOL:
            continue
        if a1 * dx + b1 * dy <= TOL and a2 * dx + b2 * dy <= TOL:
            if p1 * dx + p2 * dy > TOL:
                return True
    return False


def solve_optimal(spec: dict) -> dict:
    """Task 2. Returns {status, x, y, profit}. status in
    {"optimal", "infeasible", "unbounded"}."""
    if _is_unbounded(spec):
        return {"status": "unbounded", "x": None, "y": None, "profit": None}

    feasible_verts = [(x, y) for x, y in _candidate_vertices(spec) if _feasible(spec, x, y)]
    if not feasible_verts:
        return {"status": "infeasible", "x": None, "y": None, "profit": None}

    best_x, best_y, best_val = None, None, None
    for x, y in feasible_verts:
        val = spec["p1"] * x + spec["p2"] * y
        if best_val is None or val > best_val + TOL:
            best_x, best_y, best_val = x, y, val
    return {"status": "optimal", "x": round(best_x, 6), "y": round(best_y, 6),
           "profit": round(best_val, 6)}


def make_certificate(spec: dict, solution: dict) -> dict:
    """Task 4. Re-checkable certificate."""
    if solution["status"] != "optimal":
        return {"type": "lp_status", "certified_property": solution["status"], "spec": spec}
    return {"type": "lp_vertex_optimum",
           "certified_property": "feasible_and_optimal_over_vertices_of_bounded_feasible_region",
           "spec": spec, "claimed_x": solution["x"], "claimed_y": solution["y"],
           "claimed_profit": solution["profit"]}


def recheck_certificate(cert: dict) -> dict:
    """Task 4, production recheck. Re-derives the vertex set from scratch
    and re-checks the claim (shares the vertex-enumeration search with
    solve_optimal, per the established precedent in edge_ai_solver.py /
    csp_solver.py - Certificate Independence for LP is established
    separately by research/D2_lp_vertical/independent_checker.py, which
    shares no optimization logic with this module)."""
    spec = cert["spec"]
    if cert["type"] == "lp_status":
        if cert["certified_property"] == "unbounded":
            return {"accepted": _is_unbounded(spec), "reason": "re-checked unboundedness"}
        if cert["certified_property"] == "infeasible":
            feas = any(_feasible(spec, x, y) for x, y in _candidate_vertices(spec))
            return {"accepted": not feas, "reason": "re-checked infeasibility"}
        return {"accepted": False, "reason": f"unknown status {cert['certified_property']}"}

    x, y, claimed = cert["claimed_x"], cert["claimed_y"], cert["claimed_profit"]
    if not _feasible(spec, x, y):
        return {"accepted": False, "reason": "claimed point is infeasible"}
    recomputed = spec["p1"] * x + spec["p2"] * y
    if abs(recomputed - claimed) > TOL * max(1.0, abs(claimed)):
        return {"accepted": False, "reason": f"profit {claimed} != recomputed {recomputed}"}
    true_opt = solve_optimal(spec)
    if true_opt["status"] != "optimal":
        return {"accepted": False, "reason": f"true LP status is {true_opt['status']}, not optimal"}
    if abs(true_opt["profit"] - claimed) > TOL * max(1.0, abs(claimed)):
        return {"accepted": False,
                "reason": f"claimed {claimed} is not optimal (true optimum {true_opt['profit']})"}
    return {"accepted": True, "reason": "feasible, consistent, and optimal (vertex re-derivation)"}


# ---- Kernel-protocol adapters --------------------------------------------

class LPAttempter:
    """Contract Principle 4: the deterministic solver produces the
    candidate."""

    def attempt(self, state) -> dict:
        spec = state.formalization.get("spec")
        if spec is None:
            return {"solution": None, "tokens": 0}
        return {"solution": solve_optimal(spec), "tokens": 0}


class DeterministicLPExecutor:
    """Shape validation only - the Attempter (solver) already computed the
    answer; no further arithmetic is owed here (mirrors
    kernel/csp_solver.py's DeterministicCSPExecutor)."""

    def execute(self, state, attempt: dict) -> dict:
        solution = (attempt or {}).get("solution")
        if not isinstance(solution, dict) or "status" not in solution:
            return {"tool": "shape_check", "answer": None,
                    "tokens": (attempt or {}).get("tokens", 0)}
        return {"tool": "shape_check", "answer": solution,
                "tokens": (attempt or {}).get("tokens", 0)}


class LPCertifyingVerifier:
    """Task 3. Certifies exactly the benchmark grading predicate (feasible,
    consistent, optimal) - never a weaker property."""

    def verify(self, state, execution: dict) -> dict:
        spec = state.formalization.get("spec")
        solution = (execution or {}).get("answer")
        if spec is None:
            return {"ok": False, "trust_label": "Open", "failure_type": "formalization",
                    "signals": [{"kind": "formalization_shape", "location": "formalization",
                                 "evidence": {"detail": "no usable spec"}}]}
        if solution is None:
            return {"ok": False, "trust_label": "Open", "failure_type": "execution",
                    "signals": [{"kind": "no_candidate", "location": "attempt",
                                 "evidence": {"detail": "no solution produced"}}]}
        if solution["status"] != "optimal":
            cert = make_certificate(spec, solution)
            recheck = recheck_certificate(cert)
            if recheck["accepted"]:
                return {"ok": True, "trust_label": "Verified", "failure_type": None,
                        "signals": [], "certificate": cert, "recheck": recheck}
            return {"ok": False, "trust_label": "Open", "failure_type": "execution",
                    "signals": [{"kind": "no_candidate", "location": "solver",
                                 "evidence": {"detail": f"status={solution['status']}, "
                                             f"unverified"}}]}

        cert = make_certificate(spec, solution)
        recheck = recheck_certificate(cert)
        if recheck["accepted"]:
            return {"ok": True, "trust_label": "Verified", "failure_type": None,
                    "signals": [], "certificate": cert, "recheck": recheck}
        return {"ok": False, "trust_label": "Derived", "failure_type": "verification",
                "signals": [{"kind": "optimality_uncertified", "location": "answer",
                             "evidence": {"detail": recheck["reason"]}}],
                "certificate": cert, "recheck": recheck}
